name: pdf_viewer_2
description: A flutter plugin to display PDF.
version: 1.0.2
author: Alban Veliu <alban.veliu<@gmail.com>
homepage: https://github.com/albo1337

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

flutter:
  plugin:
    androidPackage: com.albo1337.pdfviewer
    pluginClass: PDFViewerPlugin
